stt:
  model: tiny.en
tts:
  voice: com.apple.speech.synthesis.voice.Alex
llm:
  api_key: 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
  model: mistralai/Mixtral-8x7B-Instruct-v0.1
audio:
  sample_rate: 16000
  chunk_size: 1024
logging:
  level: INFO
  path: logs/app.log